/**
 * Telemetry Contract for Vision-Only Structural Monitoring Dashboard.
 *
 * NOTE: This is a read-only conceptual adapter contract designed for future integration.
 * In this stage, all telemetry is generated by VisionSimulator in VISION-ONLY SIMULATION MODE.
 * It is NOT a direct feed from the physical webcam pipeline and does NOT represent real bridge measurements.
 */

export type TrackingQuality = "GOOD" | "DEGRADED" | "LOST";

export type MeasurementStatus =
    | "VALID"
    | "EXCESSIVE_STEP_DISPLACEMENT"
    | "EXCEEDS_FRAME_BOUNDS"
    | "TRACKING_LOST"
    | "LOW_CONFIDENCE";

export type ScenarioType = "NORMAL" | "WARNING" | "CRITICAL";

export interface FeaturePoint {
    id: number;
    baseX: number; // percentage in specimen ROI [0 - 100]
    baseY: number; // percentage in specimen ROI [0 - 100]
    currX: number; // current animated position percentage
    currY: number;
    valid: boolean;
    rejectionReason?: "FB_ERROR" | "MAD_OUTLIER" | "FRAME_BOUNDS" | null;
}

export type OperatingMode = "LIVE" | "SIMULATION";
export type AnalysisTab = "TIME_DOMAIN" | "FREQUENCY_DOMAIN" | "SPECTROGRAM" | "TRACKING_QUALITY" | "SESSION_STATS" | "ALL_VIEWS";

export interface VisionTelemetry {
    timestamp: number; // elapsed time in seconds

    // Displacement
    displacementX: number; // px in LIVE mode, mm in SIMULATION mode
    displacementY: number;
    displacementMagnitude: number;

    // Velocity
    velocityX: number; // px/s in LIVE mode, mm/s in SIMULATION mode
    velocityY: number;
    velocityMagnitude: number;

    // Acceleration
    accelerationX: number; // px/s² in LIVE mode, m/s² in SIMULATION mode
    accelerationY: number;
    accelerationMagnitude: number;

    dominantFrequency: number | null; // Hz: resonant oscillation frequency

    featureCount: number; // number of actively tracked optical features
    inlierCount: number; // number of features passing bidirectional LK + MAD filter
    forwardValidCount: number; // features passing forward LK
    backwardValidCount: number; // features passing backward LK
    rejectedCount: number; // features rejected by FB error or MAD filter
    retentionRate: number; // percentage of detected features retained [0 - 100%]

    confidence: number; // normalized tracking confidence score [0.0 - 1.0]
    madX: number; // Median Absolute Deviation in X
    madY: number; // Median Absolute Deviation in Y

    trackingQuality: TrackingQuality;
    measurementValid: boolean;
    measurementStatus: MeasurementStatus;

    scenario: ScenarioType;
    autoScenarioActive: boolean;

    // Units & Mode indicators
    isLive?: boolean;
    fps?: number;
    unit?: "px" | "mm";
    displayUnit?: "px" | "mm";
    validityReason?: MeasurementStatus;
    velocityUnit?: "px/s" | "mm/s";
    accelerationUnit?: "px/s²" | "m/s²";

    // FFT Spectrum data
    fftFrequencies?: number[];
    fftAmplitudes?: number[];
    peakFrequencyHz?: number | null;
    peakAmplitude?: number | null;

    // Baseline response deviation
    baselineFrequencyHz?: number | null;
    frequencyDeviationHz?: number | null;

    // Feature point coordinates for 2D optical visualizer (in simulation)
    features?: FeaturePoint[];
}

export interface LiveTelemetryPacket {
    timestamp: number;
    fps: number;
    frame_width: number;
    frame_height: number;
    displacement_x_px: number;
    displacement_y_px: number;
    displacement_magnitude_px: number;
    velocity_x_px_s: number;
    velocity_y_px_s: number;
    velocity_magnitude_px_s: number;
    acceleration_x_px_s2: number;
    acceleration_y_px_s2: number;
    acceleration_magnitude_px_s2: number;
    dominant_frequency_hz: number | null;
    feature_count: number;
    inlier_feature_count: number;
    rejected_feature_count: number;
    retention_rate: number;
    tracking_quality: TrackingQuality;
    measurement_valid: boolean;
    validity_reason: MeasurementStatus;
    confidence: number;
    mad_x_px: number;
    mad_y_px: number;
    baseline_frequency_hz?: number | null;
    frequency_deviation_hz?: number | null;
    fft_frequencies?: number[];
    fft_amplitudes?: number[];
    peak_frequency_hz?: number | null;
    peak_amplitude?: number | null;
    is_live: boolean;
}

export interface SessionStats {
    startTime: number;
    durationSeconds: number;
    totalFrames: number;
    validFrames: number;
    invalidFrames: number;
    validPercent: number;
    avgFps: number;
    peakDisplacement: number;
    rmsDisplacement: number;
    peakVelocity: number;
    peakAcceleration: number;
    meanConfidence: number;
    minConfidence: number;
    freqMean: number | null;
    freqMedian: number | null;
    freqMin: number | null;
    freqMax: number | null;
    freqStd: number | null;
}

export interface BaselineRecord {
    timestamp: number;
    baseline_frequency_hz: number | null;
    baseline_displacement_mag_px: number;
    baseline_velocity_mag_px_s: number;
    baseline_confidence: number;
    captured_at: string;
}

export interface SimulationEvent {
    id: string;
    timestamp: string;
    message: string;
    type: "info" | "warning" | "critical" | "tracking";
}
