/**
 * Telemetry Contract for Vision-Only Structural Monitoring Dashboard.
 *
 * NOTE: This is a read-only conceptual adapter contract designed for future integration.
 * In this stage, all telemetry is generated by VisionSimulator in VISION-ONLY SIMULATION MODE.
 * It is NOT a direct feed from the physical webcam pipeline and does NOT represent real bridge measurements.
 */

export type TrackingQuality = "GOOD" | "DEGRADED" | "LOST";

export type MeasurementStatus =
    | "VALID"
    | "EXCESSIVE_STEP_DISPLACEMENT"
    | "EXCEEDS_FRAME_BOUNDS"
    | "TRACKING_LOST";

export type ScenarioType = "NORMAL" | "WARNING" | "CRITICAL";

export interface FeaturePoint {
    id: number;
    baseX: number; // percentage in specimen ROI [0 - 100]
    baseY: number; // percentage in specimen ROI [0 - 100]
    currX: number; // current animated position percentage
    currY: number;
    valid: boolean;
}

export interface VisionTelemetry {
    timestamp: number; // elapsed simulation time in seconds

    displacementX: number; // mm (simulated structural displacement)
    displacementY: number; // mm
    displacementMagnitude: number; // mm: sqrt(dx² + dy²)

    velocityX: number; // mm/s: numerical dx/dt
    velocityY: number; // mm/s
    velocityMagnitude: number; // mm/s

    accelerationX: number; // m/s²: numerical d²x/dt²
    accelerationY: number; // m/s²
    accelerationMagnitude: number; // m/s²

    dominantFrequency: number; // Hz: resonant structural oscillation frequency

    featureCount: number; // number of actively tracked optical features

    trackingQuality: TrackingQuality;

    measurementValid: boolean;

    measurementStatus: MeasurementStatus;

    scenario: ScenarioType;

    // Feature point coordinates for 2D optical visualizer
    features: FeaturePoint[];
}

export interface SimulationEvent {
    id: string;
    timestamp: string;
    message: string;
    type: "info" | "warning" | "critical" | "tracking";
}
